"""
==============================================================
SIMI

constants.py

Constantes globales del sistema.
==============================================================
"""

# Roles de usuario
ROL_ADMINISTRADOR_MAESTRO = "ADMINISTRADOR_MAESTRO"
ROL_ADMINISTRADOR = "ADMINISTRADOR"
ROL_ANALISTA = "ANALISTA"
ROL_CONSULTA = "CONSULTA"


ROLES_SISTEMA = [
    ROL_ADMINISTRADOR_MAESTRO,
    ROL_ADMINISTRADOR,
    ROL_ANALISTA,
    ROL_CONSULTA
]


# Estados / fases del procedimiento
FASE_PROPUESTAS_RECIBIDAS = "PROPUESTAS_RECIBIDAS"
FASE_EVALUADO = "EVALUADO"
FASE_MEJOR_OFERTA_RECIBIDA = "MEJOR_OFERTA_RECIBIDA"
FASE_ADJUDICADO = "ADJUDICADO"
FASE_NO_ADJUDICADO = "NO_ADJUDICADO"
FASE_CANCELADO = "CANCELADO"
FASE_SUSPENDIDO = "SUSPENDIDO"
FASE_MODIFICADO = "MODIFICADO"
FASE_DESIERTO = "DESIERTO"


FASES_PROCEDIMIENTO = [
    FASE_PROPUESTAS_RECIBIDAS,
    FASE_EVALUADO,
    FASE_MEJOR_OFERTA_RECIBIDA,
    FASE_ADJUDICADO,
    FASE_NO_ADJUDICADO,
    FASE_CANCELADO,
    FASE_SUSPENDIDO,
    FASE_MODIFICADO,
    FASE_DESIERTO
]


# Tipos de propuesta
TIPO_PROPUESTA_INICIAL = "INICIAL"
TIPO_PROPUESTA_SUBASTA = "SUBASTA"


TIPOS_PROPUESTA = [
    TIPO_PROPUESTA_INICIAL,
    TIPO_PROPUESTA_SUBASTA
]


# Evaluación técnica
EVALUACION_POSITIVA = "POSITIVA"
EVALUACION_NEGATIVA = "NEGATIVA"


RESULTADOS_EVALUACION = [
    EVALUACION_POSITIVA,
    EVALUACION_NEGATIVA
]


# Categorías de clave
CATEGORIAS_CLAVE = [
    "COMPRA CONSOLIDADA",
    "COMPRA EMERGENTE",
    "PATENTE Y FUENTE UNICA",
    "FABOTERAPICOS",
    "MATERIAL DE CURACION"
]